// Developer Express Code Central Example:
// How to enable Gantt view for the SchedulerControl bound to collection of business objects
// 
// This is a simple example of XtraScheduler bound to collection of custom business
// objects (https://documentation.devexpress.com/#WindowsForms/CustomDocument9606)
// displaying Gantt view
// (http://documentation.devexpress.com/#WindowsForms/CustomDocument10698). This
// project also utilizes the ResourcesTree control
// (http://documentation.devexpress.com/#WindowsForms/CustomDocument10685) to
// display a hierarchy of resources and the SplitContainer control
// (http://documentation.devexpress.com/#WindowsForms/clsDevExpressXtraEditorsSplitContainerControltopic)
// to allow resizing of Scheduler and ResourceTree controls.
// 
// To accomplish this
// task, you should have three collections - for appointments, for resources and
// for appointments dependencies. All collections should implement the IBindingList
// interface. You can implement this interface manually in your custom collection,
// but we recommend you use the System.ComponentModel.BindingList<T>
// collection.
// 
// Additionally, your business objects should have properties
// suitable for mapping
// (https://documentation.devexpress.com/#WindowsForms/CustomDocument15468)to the
// corresponding properties of XtraScheduler appointments, resources and
// appointments dependencies.
// 
// See
// also:
// http://www.devexpress.com/scid=E750
// http://www.devexpress.com/scid=E3574
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=T185539

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dxT183299.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dxT183299.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
